#!/bin/bash
export CLICOLOR=1
export HISTCONTROL="ignoredups"
export HISTSIZE="2000"
export LSCOLORS=dxFxCxDxBxegedabagacad

export EDITOR="vim"
export VISUAL="vim"
export PAGER=less
export BLOCKSIZE=K
export PARINIT='w72jrT4bgqR B=.,?_A_a Q=_s>|'
export LC_CTYPE=en_US.UTF-8
export VIM_APP_DIR=/Applications
export GREP_OPTIONS='--color=auto'
export GREP_COLOR='1;33'

export LESS="-X -M -E -R"
export LS_OPTIONS="--color=yes  -F -b -T 0"

export PATH=~/bin:$PATH

[ $TERM = "screen" ] && export TERM=xterm


